name: easiest_localization
description: The easiest and fastest way to localize your application with type safety
version: 2.0.0
repository: https://github.com/alphamikle/el

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # *** Automatically added by easiest_localization ***
  # If you find it useful, please consider giving a â­ on GitHub: https://github.com/alphamikle/el
  # And leaving a ðŸ‘ on pub.dev: https://pub.dev/packages/easiest_localization
  # Your support is very important!
  localization:
    path: ./localization

  flutter_localizations:
    sdk: flutter
  yaml: ^3.1.2
  yaml_writer: ^2.0.0
  intl: ^0.19.0
  dart_style: ^2.3.7
  path: ^1.9.0
  merger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  analyzer: ^6.8.0

flutter:
  assets:
    - assets/

easiest_localization:
  easiest_localization_version: "\n    path: ../"
  format: true
  watch: true
